spring:
  application:
    name: fitinside
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

  # H2 DB 설정
  datasource:
    driver-class name: org.h2.Driver
    url: jdbc:h2:mem:fitinside
    username: sa
    password: ''

  # H2 console 설정
  h2:
    console:              # h2 DB를 웹에서 관리할 수 있는 기능
      enabled: true       # h2 console 사용 여부
      path: /h2-console   # h2 console 접속 주소

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: create    # DB 초기화 전략
    properties:
      hibernate:
        format_sql: true  # 쿼리 로그 포맷 (저렬)
        show_sql: true    # 쿼리 로그 출력

jwt:
  secret: 'KC2XjwwyNLVedIxmh1ys3cOxp5vImhoEDygJdFTcWd3NE3H3pAVnEhxAyKai0oOAwgxkvnb1xnb9dicv8gisd3sAfB9aVd0'

cloud:
  aws:
    credentials:
      accessKey: AKIAZI2LDLMW2DIHF6RH
      secretKey: 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
    s3:
      bucketName: fitinside
    region:
      static: ap-northeast-2
    stack:
      auto: false